SELECT SKU, SKU_DESCRIPTION FROM INVENTORY;

SELECT SKU_DESCRIPTION, SKU FROM INVENTORY;

SELECT WarehouseId FROM INVENTORY;

SELECT UNIQUE WarehouseId FROM INVENTORY;

SELECT WarehouseId, SKU, SKU_DESCRIPTION, QuantityOnHand, QuantityOnOrder FROM INVENTORY;

SELECT * FROM INVENTORY;

SELECT * FROM INVENTORY WHERE QuantityOnHand > 0;

SELECT SKU, SKU_DESCRIPTION FROM INVENTORY WHERE QuantityOnHand = 0;

SELECT SKU, SKU_DESCRIPTION FROM INVENTORY WHERE QuantityOnHand = 0 ORDER BY WAREHOUSEID ASC;

SELECT SKU, SKU_DESCRIPTION, WarehouseId FROM INVENTORY WHERE QuantityOnHand > 0 ORDER BY WAREHOUSEID DESC, SKU ASC;

SELECT SKU, SKU_DESCRIPTION, WarehouseId FROM INVENTORY WHERE QuantityOnHand = 0 and QuantityOnOrder > 0 ORDER BY WarehouseId DESC, SKU ASC;

SELECT SKU, SKU_DESCRIPTION, WarehouseId FROM INVENTORY WHERE QuantityOnHand = 0 or QuantityOnOrder = 0 ORDER BY WarehouseId DESC, SKU ASC;

SELECT SKU, SKU_DESCRIPTION, WarehouseId, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand > 1 and  quantityOnHand < 10;

SELECT SKU, SKU_DESCRIPTION, WarehouseId, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand BETWEEN 2 and 9;

SELECT DISTINCT SKU, SKU_DESCRIPTION FROM INVENTORY WHERE SKU_DESCRIPTION LIKE 'Half-Dome%';

SELECT DISTINCT SKU, SKU_DESCRIPTION FROM INVENTORY WHERE SKU_DESCRIPTION LIKE '%Climb%';

SELECT DISTINCT SKU, SKU_DESCRIPTION FROM INVENTORY WHERE SKU_DESCRIPTION LIKE '__d%';

SELECT MIN(QuantityOnHand) AS MIN_QUANTITY, MAX(QuantityOnHand) AS MAX_QUANTITY, AVG(QuantityOnHand) AS Average_quantity, COUNT(QuantityOnHand) as COUNT_QUANTITY, SUM(QuantityOnHand) AS SUM_QUANTITY FROM INVENTORY;


